name: Deploy Infra

on: 
  workflow_dispatch:
     inputs:
      environment:
        description: "Environment variable"
        required: true
      alias:
        description: "Alias variable"
        required: true

jobs:
    deploy-infra:

      runs-on: ubuntu-latest
      
      defaults:
        run:
          working-directory: ./client

      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: sa-east-1

        - name: Init terraform
          run: |
            terraform init

        - name: Run terraform apply
          run: |
            terraform apply -auto-approve -var='common={"environment"="${{github.event.inputs.environment}}", "alias"="${{github.event.inputs.alias}}"}'

        - name: Save state file on S3
          run: |
            aws s3 cp terraform.tfstate s3://financial-terraform-states/${{github.event.inputs.alias}}_${{github.event.inputs.environment}}/terraform.tfstate